openapi: "3.0.3"
info:
  title: "Amount-counter API"
  description: "Small API for requesting data or file"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /api/getProducts:
    get:
      tags:
        - Controller
      description: "Get products list"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsList'
        "500":
          description: "Internal server error"
  /api/getSummary:
    post:
      tags:
        - Controller
      description: "Download products summary pdf file"
      requestBody:
        description: Ids list
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsRequestDto'
      responses:
        "200":
          description: "OK"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: "Bad request"
        "500":
          description: "Internal server error"
components:
  schemas:
    IdsRequestDto:
      title: ProductRequestBody
      type: object
      properties:
        ids:
          type: array
          example: [ "5d6aa284-0f05-49f5-b563-f83c3d2ffd90","77ac3a82-6a9c-427e-b281-a0a73b8a5847","1e0b7134-cfd1-4a0b-89b2-9c2616478f36" ]
          items:
            type: string
            example: "1e0b7134-cfd1-4a0b-89b2-9c2616478f36"
    Product:
      title: Product
      type: object
      properties:
        id:
          type: string
          example: "1e0b7134-cfd1-4a0b-89b2-9c2616478f36"
        name:
          type: string
          example: "Diablo IV"
        amount:
          type: integer
          example: 900
    ProductsList:
      title: ProductsList
      type: array
      items:
        $ref: '#/components/schemas/Product'
